### ISSUE TITLE
Add bottom and top image dimensions check to blend entry points

### ISSUE THREAD

**Issue by joao-conde** [hivesolutions/pconvert#5]
@joamag 

## Description

PConvert works for images of the same dimensions (width and height). However, blending images with different dimensions should return an error and not segfault. This causes issues for clients of the API (whether in Python or in C) where the program just segfaults.

The [`blend_images`](https://github.com/hivesolutions/pconvert/blob/master/src/pconvert/pconvert.c#L387) function should make a simple verification to the bottom and top images dimensions and check if they are equal. If not, we can return with an exit code. Notice that it already returns an ERROR_T (just an int) but it is always the NORMAL one unless it segfaults.

When images do not have the same size, this pointer arithmetic is guaranteed to SEGFAULT:

- https://github.com/hivesolutions/pconvert/blob/master/src/pconvert/pconvert.c#L400
- https://github.com/hivesolutions/pconvert/blob/master/src/pconvert/pconvert.c#L403

##  Proposal

Add an images dimensions check to all blend entry points to avoid invalid pointer arithmetic.

**Comment by joao-conde** [comment]
For reference, the way PConvert rust deals with this is: https://github.com/ripe-tech/pconvert-rust/blob/6f13b2c0e09762e8a609199b3212d112dabb030c/src/blending/mod.rs#L102

`.zip` will take both iterators and "fill" the shortest one with default values for the elements. Hence, if a smaller image is provided, this basically merges both by "aligning the shortest one to the top left" and using RGBA(0,0,0,0) for the filling.

**Comment by joamag** [comment]
@joao-conde Pre-validation has been added, but I'm still pending some incorrect image size tests to close this issue

**Comment by joamag** [comment]
Yup got it working. Closing this issue as fixed.

<img width="504" alt="Screenshot 2022-11-28 at 23 55 27" src="https://user-images.githubusercontent.com/25441/204405339-2005c3a3-d4cb-4fba-b819-517250f9bf44.png">

**Comment by joamag** [comment]
@joao-conde pconvert-python 0.4.5 already includes this fix

**Comment by joao-conde** [comment]
Nice! 🚀
